# Generated by Django 5.1.2 on 2024-11-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_user_is_active_user_is_staff_user_last_login_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="Jean", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
